title: Coderic
email: info@coderic.co.ve
description: Corporacion Orientada al Desarrollo Estratégico de Recursos de Información Comercial
author: Coderic
logo: /images/logo43.png


twitter_username: Coderic
github_username:  Coderic

lang: es
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate